const CONFIG = {
    introTitle: 'M ơi!',
    btnIntro: 'Gì thế',
    title: 'M có muốn gần t hơn không ?',
    desc: '❤❤❤❤❤ ',
    btnYes: 'T muốnnnn ❤',
    btnNo: 'Không muốnnn :3',
    question:'Vì sao m muốn gần t hơn <3',
    btnReply: 'Gửi <3',
    reply: ' Vì m đặc biệt ',
    mess: 'T biết, m cũng là người đặc biệt mà <3',
    messDesc: 'Mình tìm hỉu nheee :P',
    btnAccept: 'Okiiiii lun <3',
    link:'https://www.facebook.com/profile.php?id=100026500275555',
}
